{% set version = "0.4.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-labeling
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/labeling_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/labeling/labeling_{{ version }}.tar.gz
  sha256: c62f4fc2cc74377d7055903c5f1913b7295f7587456fe468592738a483e264f2

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('labeling')"           # [not win]
    - "\"%R%\" -e \"library('labeling')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=labeling
  license: MIT
  summary: Functions which provide a range of axis labeling algorithms.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: labeling
# Type: Package
# Title: Axis Labeling
# Version: 0.4.2
# Date: 2020-10-15
# Author: Justin Talbot,
# Maintainer: Nuno Sempere <nuno.semperelh@gmail.com>
# Description: Functions which provide a range of axis labeling algorithms.
# License: MIT + file LICENSE | Unlimited
# Collate: 'labeling.R'
# NeedsCompilation: no
# Imports: stats, graphics
# Packaged: 2020-10-18 12:56:46 UTC; nuno
# Repository: CRAN
# Date/Publication: 2020-10-20 07:00:09 UTC
