appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: fiHFmsXpxu/oYi7qd9Ct9IqyVKUWh9Yr2yEMkcfIlUChZSptt9b8ubENdUMgvs4+xS3HifrkqYHeDpF9z2w3fQC80HJEkgbvi7ZVG7uXGCkXBQDiomVWidsoPC9grCY1Us3ga+UdRcZRR/YWf+Z5C3VH+A6J+cgs1hwjfekyGIDbHnnWMjcwLaO7kr8g5JetRuWf16uyg12fBZwQKnJ4IPrtd+6tSMlsWZKt3ewR9zvUYYfsy3PCsU1+EP62Hx4BnlAh44NuBmH+JmUddbpCmzazcRS3NKyE7/VUYhd58/Oxjbhw9DtCekqsVhII7N1gXxwm+LK1EndIRHMynZfrnnaeJaDAf/Qlu9APnpd9d9XOa09zQ/7vqi0jFgYptGbp+EWvdTGrCBEqt+6IUI5vJlslCeBbrT0oLv0eTVeQuYidj1Ct7RYEgfXvctAyvvMeurSrTtGhN9RPR79Q+Z5MopOyT+qeA6GqbtXNsrtCQ3qd75uKXWWta2o17flOYsiUGNAtc6ZQKomaf6Hqutep5gngMaKoueqIqi7DtExCHcUN6XFz8gFkD7HDtk5Gl3ZCfz6xfXPcMnrqy64Ssa9XkG1ZOnUCL6iYmujKhwEo0W56ZfEQKOhErSlKrSiCED8wGWCSGxmny3vfEH2hYxjuup2lxMDQqdVzpyiOhcVtqmo=
conda_forge_output_validation: true
